// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/auth_svc/infrastructure/pb/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserName        string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,5,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_pkg_auth_svc_infrastructure_pb_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_auth_svc_infrastructure_pb_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_pkg_auth_svc_infrastructure_pb_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_auth_svc_infrastructure_pb_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SignUpResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_auth_svc_infrastructure_pb_auth_proto protoreflect.FileDescriptor

const file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDesc = "" +
	"\n" +
	")pkg/auth_svc/infrastructure/pb/auth.proto\x12\n" +
	"auth_proto\"\x9b\x01\n" +
	"\rSignUpRequest\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12(\n" +
	"\x0fConfirmPassword\x18\x05 \x01(\tR\x0fConfirmPassword\"J\n" +
	"\x0eSignUpResponse\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\"\n" +
	"\fErrorMessage\x18\x02 \x01(\tR\fErrorMessage2R\n" +
	"\vAuthService\x12C\n" +
	"\n" +
	"UserSignUp\x12\x19.auth_proto.SignUpRequest\x1a\x1a.auth_proto.SignUpResponseB\"Z ./pkg/auth_svc/infrastructure/pbb\x06proto3"

var (
	file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDescOnce sync.Once
	file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDescData []byte
)

func file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDescGZIP() []byte {
	file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDescOnce.Do(func() {
		file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDesc), len(file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDesc)))
	})
	return file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDescData
}

var file_pkg_auth_svc_infrastructure_pb_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_auth_svc_infrastructure_pb_auth_proto_goTypes = []any{
	(*SignUpRequest)(nil),  // 0: auth_proto.SignUpRequest
	(*SignUpResponse)(nil), // 1: auth_proto.SignUpResponse
}
var file_pkg_auth_svc_infrastructure_pb_auth_proto_depIdxs = []int32{
	0, // 0: auth_proto.AuthService.UserSignUp:input_type -> auth_proto.SignUpRequest
	1, // 1: auth_proto.AuthService.UserSignUp:output_type -> auth_proto.SignUpResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_auth_svc_infrastructure_pb_auth_proto_init() }
func file_pkg_auth_svc_infrastructure_pb_auth_proto_init() {
	if File_pkg_auth_svc_infrastructure_pb_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDesc), len(file_pkg_auth_svc_infrastructure_pb_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_auth_svc_infrastructure_pb_auth_proto_goTypes,
		DependencyIndexes: file_pkg_auth_svc_infrastructure_pb_auth_proto_depIdxs,
		MessageInfos:      file_pkg_auth_svc_infrastructure_pb_auth_proto_msgTypes,
	}.Build()
	File_pkg_auth_svc_infrastructure_pb_auth_proto = out.File
	file_pkg_auth_svc_infrastructure_pb_auth_proto_goTypes = nil
	file_pkg_auth_svc_infrastructure_pb_auth_proto_depIdxs = nil
}
